AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Test Lambda Authorizer using An API Gateway

Globals:
  Api:
    OpenApiVersion: 3.0.1
  Function:
    Runtime: nodejs12.x
    Timeout: 15

Parameters:
  PublicKey:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/param/test/public-key'

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: 'default'
      Auth:
        Authorizers:
          LambdaAuth:
            FunctionArn: !GetAtt AuthFunction.Arn
            Identity:
              Header: Authorization
              ValidationExpression: 'Bearer .*'
              ReauthorizeEvery: 30
        DefaultAuthorizer: LambdaAuth
  Function1:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      Handler: echo.handler
      CodeUri: 'src/echo.js'
      Events:
        EchoRequest:
          Type: Api
          Properties:
            Path: /echo
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
  Function2:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      Handler: echo2.handler
      CodeUri: 'src/echo2.js'
      Events:
        EchoRequest:
          Type: Api
          Properties:
            Path: /echo2
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
  ProxyFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      Handler: echo.handler
      CodeUri: 'src/echo.js'
      Events:
        Proxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
            RestApiId:
              Ref: ApiGatewayApi
  AuthFunctionNodeModules:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: 'layer/.'
      CompatibleRuntimes:
        - nodejs12.x
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      Handler: authorizer.handler
      CodeUri: 'src/authorizer.js'
      Layers:
        - !Ref AuthFunctionNodeModules
      Environment:
        Variables:
          JWT_PUBLIC_KEY: !Ref PublicKey
          NODE_PATH: '/opt/nodejs/node_modules/'

Outputs:
  DataEndpoint:
    Description: "API endpoint"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/default"